version: "3.9"
services:

  back:
    build:
      context: ./
    command: npm run start:dev
    volumes:
      - .env/:/api/.env
      - ./node_modules:/api/node_modules
      - ./src/:/api/src
      - ./libs/:/api/libs
    depends_on:
      - db
      - redis
    ports:
      - ${PORT}:${PORT}

  db:
    image: postgres:15.3
    container_name: postgres
    hostname: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    restart: always
    logging:
      driver: none

volumes:
  postgres-data:

# networks:
#   test:
#     driver: bridge
